#!/bin/bash
##### save images for each class
cd mosaicRelated/
# E_
# python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/Ei/ Ei
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/Ec/ Ec
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/Er/ Er
# S_
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/Sa/ Sa
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/Sb/ Sb
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/Sc/ Sc
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/Sd/ Sd
# SB_
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/SBa/ SBa
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/SBb/ SBb
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/SBc/ SBc
python saveImagesFromFits.py ../galaxyZoo2/catalogs/SDSS_DR7_k5_merged_GZ2_11classes.csv dr7objid gz2class ../../CyMorph/stamps/ ../GZ2-byClasses-imgs/k5/11classes/SBd/ SBd
##### generate compressed files
cd ..
### k5
# simple tar (imgs were generated by k5 catalog)
# cd GZ2-byClasses-imgs/k5/11classes/Ei/ && tar -zcvf ../Ei.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/Ec/ && tar -zcvf ../Ec.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/Er/ && tar -zcvf ../Er.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/Sa/ && tar -zcvf ../Sa.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/Sb/ && tar -zcvf ../Sb.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/Sc/ && tar -zcvf ../Sc.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/Sd/ && tar -zcvf ../Sd.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/SBa/ && tar -zcvf ../SBa.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/SBb/ && tar -zcvf ../SBb.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/SBc/ && tar -zcvf ../SBc.tgz * && cd ../../../../
cd GZ2-byClasses-imgs/k5/11classes/SBd/ && tar -zcvf ../SBd.tgz * && cd ../../../../
### k10
# python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv Ei GZ2-byClasses-imgs/k5/11classes/Ei/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv Ec GZ2-byClasses-imgs/k5/11classes/Ec/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv Er GZ2-byClasses-imgs/k5/11classes/Er/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv Sa GZ2-byClasses-imgs/k5/11classes/Sa/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv Sb GZ2-byClasses-imgs/k5/11classes/Sb/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv Sc GZ2-byClasses-imgs/k5/11classes/Sc/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv Sd GZ2-byClasses-imgs/k5/11classes/Sd/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv SBa GZ2-byClasses-imgs/k5/11classes/SBa/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv SBb GZ2-byClasses-imgs/k5/11classes/SBb/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv SBc GZ2-byClasses-imgs/k5/11classes/SBc/ GZ2-byClasses-imgs/k10/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k10_merged_GZ2_11classes.csv SBd GZ2-byClasses-imgs/k5/11classes/SBd/ GZ2-byClasses-imgs/k10/11classes/
### k20
# python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv Ei GZ2-byClasses-imgs/k5/11classes/Ei/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv Ec GZ2-byClasses-imgs/k5/11classes/Ec/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv Er GZ2-byClasses-imgs/k5/11classes/Er/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv Sa GZ2-byClasses-imgs/k5/11classes/Sa/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv Sb GZ2-byClasses-imgs/k5/11classes/Sb/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv Sc GZ2-byClasses-imgs/k5/11classes/Sc/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv Sd GZ2-byClasses-imgs/k5/11classes/Sd/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv SBa GZ2-byClasses-imgs/k5/11classes/SBa/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv SBb GZ2-byClasses-imgs/k5/11classes/SBb/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv SBc GZ2-byClasses-imgs/k5/11classes/SBc/ GZ2-byClasses-imgs/k20/11classes/
python compressImgsByClassZoo2.py catalogs/input/SDSS_DR7_k20_merged_GZ2_11classes.csv SBd GZ2-byClasses-imgs/k5/11classes/SBd/ GZ2-byClasses-imgs/k20/11classes/
##### copy files to External HD 